CREATE TABLE IF NOT EXISTS omdb_metadata (
    imdb_id VARCHAR(20) PRIMARY KEY,
    title VARCHAR(255),
    year VARCHAR(10),
    rated VARCHAR(10),
    released DATE,
    runtime VARCHAR(50),
    genre VARCHAR(255),
    director VARCHAR(255),
    writer TEXT,
    actors TEXT,
    plot TEXT,
    language VARCHAR(100),
    country VARCHAR(100),
    awards TEXT,
    poster TEXT,
    metascore VARCHAR(10),
    imdb_rating NUMERIC(3,1),
    imdb_votes VARCHAR(20),
    type VARCHAR(20),
    dvd VARCHAR(50),
    box_office VARCHAR(50),
    production VARCHAR(100),
    website VARCHAR(255)
);
